name: Create Archive
on: [workflow_dispatch, push]
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy Template Folder
        run: cp -r ./template ./quickrn-template-bottom-tabs
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'quickrn-template-bottom-tabs.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
          path: './quickrn-template-bottom-tabs'
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: 'quickrn-template-bottom-tabs.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'v1.0'
